/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Time = IDL.Int;
export const Story = IDL.Record({
  'title' : IDL.Text,
  'content' : IDL.Text,
  'wordCount' : IDL.Nat,
  'createdAt' : Time,
  'genre' : IDL.Text,
});
export const AvatarConfig = IDL.Record({
  'jsonConfig' : IDL.Text,
  'name' : IDL.Text,
});
export const MovieStoryboard = IDL.Record({
  'title' : IDL.Text,
  'script' : IDL.Text,
  'style' : IDL.Text,
  'genre' : IDL.Text,
  'prompt' : IDL.Text,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'deleteAvatar' : IDL.Func([IDL.Text], [], []),
  'deleteMovie' : IDL.Func([IDL.Text], [], []),
  'deleteStory' : IDL.Func([IDL.Text], [], []),
  'getAllUserItems' : IDL.Func(
      [],
      [IDL.Vec(Story), IDL.Vec(AvatarConfig), IDL.Vec(MovieStoryboard)],
      ['query'],
    ),
  'getAvatars' : IDL.Func([], [IDL.Vec(AvatarConfig)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getMovies' : IDL.Func([], [IDL.Vec(MovieStoryboard)], ['query']),
  'getStories' : IDL.Func([], [IDL.Vec(Story)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveAvatar' : IDL.Func([AvatarConfig], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'saveMovie' : IDL.Func([MovieStoryboard], [], []),
  'saveStory' : IDL.Func([Story], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Time = IDL.Int;
  const Story = IDL.Record({
    'title' : IDL.Text,
    'content' : IDL.Text,
    'wordCount' : IDL.Nat,
    'createdAt' : Time,
    'genre' : IDL.Text,
  });
  const AvatarConfig = IDL.Record({
    'jsonConfig' : IDL.Text,
    'name' : IDL.Text,
  });
  const MovieStoryboard = IDL.Record({
    'title' : IDL.Text,
    'script' : IDL.Text,
    'style' : IDL.Text,
    'genre' : IDL.Text,
    'prompt' : IDL.Text,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'deleteAvatar' : IDL.Func([IDL.Text], [], []),
    'deleteMovie' : IDL.Func([IDL.Text], [], []),
    'deleteStory' : IDL.Func([IDL.Text], [], []),
    'getAllUserItems' : IDL.Func(
        [],
        [IDL.Vec(Story), IDL.Vec(AvatarConfig), IDL.Vec(MovieStoryboard)],
        ['query'],
      ),
    'getAvatars' : IDL.Func([], [IDL.Vec(AvatarConfig)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getMovies' : IDL.Func([], [IDL.Vec(MovieStoryboard)], ['query']),
    'getStories' : IDL.Func([], [IDL.Vec(Story)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveAvatar' : IDL.Func([AvatarConfig], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'saveMovie' : IDL.Func([MovieStoryboard], [], []),
    'saveStory' : IDL.Func([Story], [], []),
  });
};

export const init = ({ IDL }) => { return []; };