/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface AvatarConfig { 'jsonConfig' : string, 'name' : string }
export interface MovieStoryboard {
  'title' : string,
  'script' : string,
  'style' : string,
  'genre' : string,
  'prompt' : string,
}
export interface Story {
  'title' : string,
  'content' : string,
  'wordCount' : bigint,
  'createdAt' : Time,
  'genre' : string,
}
export type Time = bigint;
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'deleteAvatar' : ActorMethod<[string], undefined>,
  'deleteMovie' : ActorMethod<[string], undefined>,
  'deleteStory' : ActorMethod<[string], undefined>,
  'getAllUserItems' : ActorMethod<
    [],
    [Array<Story>, Array<AvatarConfig>, Array<MovieStoryboard>]
  >,
  'getAvatars' : ActorMethod<[], Array<AvatarConfig>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getMovies' : ActorMethod<[], Array<MovieStoryboard>>,
  'getStories' : ActorMethod<[], Array<Story>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveAvatar' : ActorMethod<[AvatarConfig], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'saveMovie' : ActorMethod<[MovieStoryboard], undefined>,
  'saveStory' : ActorMethod<[Story], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];